apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "name" . | quote }}
  labels:
    component: app
{{ include "helm-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: app
{{ include "common-labels" . | indent 8 }}
    spec:
      containers:
      - name: app
        image: {{ include "image" . | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          - name: MANDRILL_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "name" . | quote }}
                key: "mandrill-key"
        ports:
          - containerPort: 9153
            name: metrics
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 15
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000    

