apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    release: {{ .Release.Name | quote }}
    prometheus: devops
{{ include "common-labels" . | indent 4 }}
spec:
  ports:
    - port: 9153
      protocol: TCP
      name: metrics
      targetPort: metrics
  selector:
{{ include "common-labels" . | indent 4 }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "name" . }}
  labels:
    prometheus: devops
    release: {{ .Release.Name | quote }}
{{ include "common-labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      prometheus: devops
      release: {{ .Release.Name | quote }}
{{ include "common-labels" . | indent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 15s